#The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

#1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

#Let us list the factors of the first seven triangle numbers:

# 1: 1
# 3: 1,3
# 6: 1,2,3,6
#10: 1,2,5,10
#15: 1,3,5,15
#21: 1,3,7,21
#28: 1,2,4,7,14,28
#We can see that 28 is the first triangle number to have over five divisors.

#What is the value of the first triangle number to have over five hundred divisors?
#Answer: 76576500

import math
import numpy

x = 1
natural_num = []
num_div_count = 0

while num_div_count < 500:
    num_div_count = 0
    natural_num.append(x)
    tri_num = numpy.sum(natural_num)
    for i in range(1,int(round(math.sqrt(tri_num),0))+1):
        if (tri_num%i) == 0:
            num_div_count += 1
    num_div_count *= 2
    x+=1
print(tri_num)
