#Problem 2
#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
#Answer: 4613732

num_list = [1,2]
num_list_even = []

x = 0

while x < 4000000:
    x = num_list[len(num_list)-1] + num_list[len(num_list)-2]
    num_list.append(x)


for num in num_list:
    if num % 2 == 0:
        num_list_even.append(num)

print(sum(num_list_even))
